export const ITEMS_TRE = {
  it: [
    { id: 1, testo: 'Quando devo prendere una decisione importante, elenco mentalmente o per iscritto vantaggi e svantaggi prima di scegliere.' },
    { id: 2, testo: 'Riesco a percepire lo stato d\'animo di una persona ancora prima che lo esprima a parole.' },
    { id: 3, testo: 'Ritengo che le emozioni altrui possano interferire con la formulazione di un giudizio oggettivo.' },
    { id: 4, testo: 'Mi sento profondamente coinvolto/a quando una persona cara mi racconta un problema personale.' },
    { id: 5, testo: 'Preferisco basare le mie opinioni su dati statistici piuttosto che su testimonianze personali.' },
    { id: 6, testo: 'In una discussione, valuto attentamente come le mie parole faranno sentire l\'interlocutore prima di pronunciarle.' },
    { id: 7, testo: 'Nei conflitti, la mia priorità è stabilire chi ha ragione sui fatti oggettivi.' },
    { id: 8, testo: 'Le decisioni che preservano l\'armonia del gruppo sono spesso le più sagge nel lungo periodo.' },
    { id: 9, testo: 'Sono disposto/a a contestare apertamente un\'idea che ritengo errata, anche se proviene da un amico stretto.' },
    { id: 10, testo: 'Le scelte più importanti della mia vita sono state guidate principalmente da ciò che "sentivo giusto".' },
    { id: 11, testo: 'Mantengo lucidità e distacco anche in situazioni emotivamente intense o stressanti.' },
    { id: 12, testo: 'Mi capita di commuovermi facilmente leggendo libri, guardando film o ascoltando le storie altrui.' },
    { id: 13, testo: 'La coerenza logica di un ragionamento è un valore che considero prioritario.' },
    { id: 14, testo: 'Quando qualcuno mi parla, presto più attenzione al tono di voce e alla postura che al contenuto verbale.' },
    { id: 15, testo: 'Diffido delle decisioni prese basandosi esclusivamente sull\'istinto o sulle sensazioni.' },
    { id: 16, testo: 'L\'empatia è la qualità che apprezzo maggiormente nelle persone con cui mi rapporto.' },
    { id: 17, testo: 'Una soluzione efficace è sempre preferibile a una soluzione semplicemente "gentile" ma meno efficace.' },
    { id: 18, testo: 'Faccio fatica a prendere decisioni che potrebbero ferire qualcuno, anche quando sono oggettivamente necessarie.' },
    { id: 19, testo: 'Analizzo i miei errori in modo distaccato, concentrandomi sulle cause e sui correttivi piuttosto che sul senso di colpa.' },
    { id: 20, testo: 'Ricordo con grande precisione le emozioni provate in determinati momenti del mio passato.' },
    { id: 21, testo: 'Apprezzo le persone dirette e schiette, anche quando il loro modo di esprimersi può risultare brusco.' },
    { id: 22, testo: 'Tendo spontaneamente ad assumere il ruolo di mediatore tra opinioni divergenti per evitare tensioni.' },
    { id: 23, testo: 'Quando leggo una notizia rilevante, verifico le fonti prima di formarmi un\'opinione definitiva.' },
    { id: 24, testo: 'Le mie prime impressioni intuitive sulle persone si rivelano accurate nella maggior parte dei casi.' },
    { id: 25, testo: 'Considero poco produttive le discussioni che si soffermano a lungo sui sentimenti dei partecipanti.' },
    { id: 26, testo: 'Valuto sempre il "clima emotivo" di un ambiente prima di esprimere la mia opinione.' },
    { id: 27, testo: 'Preferisco ricevere un feedback duro ma onesto piuttosto che uno gentile ma vago.' },
    { id: 28, testo: 'Mi adatto con naturalezza all\'umore e all\'energia delle persone con cui sto interagendo.' },
    { id: 29, testo: 'Le regole e le procedure esistono per essere rispettate, anche quando appaiono scomode o impopolari.' },
    { id: 30, testo: 'Sono disposto/a a fare eccezioni alle regole quando una persona sta attraversando un momento difficile.' },
  ],
  en: [
    { id: 1, testo: 'When I need to make an important decision, I mentally or in writing list pros and cons before choosing.' },
    { id: 2, testo: 'I can perceive someone\'s emotional state before they express it in words.' },
    { id: 3, testo: 'I believe others\' emotions can interfere with forming an objective judgment.' },
    { id: 4, testo: 'I feel deeply involved when someone close to me tells me about a personal problem.' },
    { id: 5, testo: 'I prefer to base my opinions on statistical data rather than personal testimonies.' },
    { id: 6, testo: 'In a discussion, I carefully consider how my words will make the other person feel before saying them.' },
    { id: 7, testo: 'In conflicts, my priority is to establish who is right on the objective facts.' },
    { id: 8, testo: 'Decisions that preserve group harmony are often the wisest ones in the long run.' },
    { id: 9, testo: 'I am willing to openly challenge an idea I consider wrong, even if it comes from a close friend.' },
    { id: 10, testo: 'The most important choices in my life were guided primarily by what I "felt was right".' },
    { id: 11, testo: 'I maintain clarity and detachment even in emotionally intense or stressful situations.' },
    { id: 12, testo: 'I tend to be moved easily when reading books, watching films, or listening to others\' stories.' },
    { id: 13, testo: 'Logical coherence in reasoning is a value I consider a priority.' },
    { id: 14, testo: 'When someone speaks to me, I pay more attention to tone of voice and posture than to verbal content.' },
    { id: 15, testo: 'I distrust decisions made based exclusively on instinct or feelings.' },
    { id: 16, testo: 'Empathy is the quality I appreciate most in the people I interact with.' },
    { id: 17, testo: 'An effective solution is always preferable to a simply "kind" but less effective one.' },
    { id: 18, testo: 'I struggle to make decisions that might hurt someone, even when they are objectively necessary.' },
    { id: 19, testo: 'I analyze my mistakes in a detached way, focusing on causes and corrections rather than guilt.' },
    { id: 20, testo: 'I remember with great precision the emotions I felt at certain moments of my past.' },
    { id: 21, testo: 'I appreciate direct and frank people, even when their manner of expression can be blunt.' },
    { id: 22, testo: 'I naturally tend to take on the role of mediator between divergent opinions to avoid tension.' },
    { id: 23, testo: 'When I read relevant news, I verify sources before forming a definitive opinion.' },
    { id: 24, testo: 'My first intuitive impressions about people prove accurate in most cases.' },
    { id: 25, testo: 'I consider discussions that dwell too long on participants\' feelings unproductive.' },
    { id: 26, testo: 'I always assess the "emotional climate" of an environment before expressing my opinion.' },
    { id: 27, testo: 'I prefer to receive harsh but honest feedback rather than gentle but vague feedback.' },
    { id: 28, testo: 'I naturally adapt to the mood and energy of the people I am interacting with.' },
    { id: 29, testo: 'Rules and procedures exist to be followed, even when they appear inconvenient or unpopular.' },
    { id: 30, testo: 'I am willing to make exceptions to rules when someone is going through a difficult time.' },
  ],
}

export const SCALA_TRE = {
  it: [
    { val: 0, label: 'Sempre o spesso vero' },
    { val: 1, label: 'Abbastanza vero' },
    { val: 2, label: 'Abbastanza falso' },
    { val: 3, label: 'Sempre o spesso falso' },
  ],
  en: [
    { val: 0, label: 'Always or often true' },
    { val: 1, label: 'Fairly true' },
    { val: 2, label: 'Fairly false' },
    { val: 3, label: 'Always or often false' },
  ],
}
