export const SCENARI = [
  {
    id: 1,
    cluster: 'standard',
    titolo: 'Il ritardo che non dipende da te',
    testo: 'Sei atteso/a in un posto importante. Il mezzo su cui viaggi subisce un ritardo di 40 minuti senza spiegazioni. Non puoi fare nulla per accelerare la situazione.\n\nNei primi tre minuti, cosa fai concretamente?',
    opzioni: {
      A: 'Scrivi un messaggio preciso a chi ti aspetta: stima del ritardo, proposta alternativa, tono neutro.',
      B: 'Contatti subito l\'altra persona, trasmettendo involontariamente la tua agitazione nel tono o nelle parole.',
      C: 'Non fai nulla. Aspetti. Non vedi l\'utilità di comunicare qualcosa che non puoi controllare.',
      D: 'Comunichi il ritardo in modo calibrato, poi usi il tempo disponibile per qualcosa di produttivo.',
    },
  },
  {
    id: 2,
    cluster: 'standard',
    titolo: 'Il dispositivo che smette di funzionare',
    testo: 'Stai per completare qualcosa di importante quando il dispositivo si blocca. Potresti aver perso parte del lavoro.\n\nCosa fai nei primi due minuti?',
    opzioni: {
      A: 'Procedi metodicamente: verifichi i backup, i file temporanei, lo storico del cloud. Nessuna parola fuori posto.',
      B: 'Esprimi il tuo disappunto ad alta voce o verso chi ti è vicino, anche se non hanno alcuna responsabilità.',
      C: 'Rimani immobile più del necessario, come in attesa che qualcosa si risolva da solo.',
      D: 'Recuperi la calma attiva: cerchi i backup, valuti il danno reale, stimi il tempo di ripristino senza catastrofizzare.',
    },
  },
  {
    id: 3,
    cluster: 'standard',
    titolo: 'Il piano che si disintegra all\'ultimo minuto',
    testo: 'Una struttura che hai costruito con cura — un viaggio, un evento, un progetto — collassa nelle ultime ore prima della realizzazione, per cause non imputabili a te.\n\nNei primi minuti dopo aver ricevuto la notizia, cosa fai?',
    opzioni: {
      A: 'Apri immediatamente le opzioni alternative e cominci a ricostruire un percorso operativo nuovo. Il tempo per il rimpianto verrà dopo, se verrà.',
      B: 'Resti bloccato/a in un loop di ricostruzione mentale di "se solo" — quello che doveva andare diversamente — prima di riuscire a passare all\'azione.',
      C: 'Lasci andare il piano senza tentativo di recupero. Non valuti veramente le alternative: il tuo investimento si è disinnescato in un secondo.',
      D: 'Riconosci il colpo, lasci uno spazio breve alla frustrazione, e quasi in parallelo ricostruisci una versione minore ma percorribile di quello che era pianificato.',
    },
  },
  {
    id: 4,
    cluster: 'standard',
    titolo: 'L\'errore professionale che tutti vedono',
    testo: 'Hai commesso un errore significativo in un contesto lavorativo. È visibile. Colleghi o superiori ne sono consapevoli. Non si può minimizzare né nascondere.\n\nCosa fai nelle ore immediatamente successive?',
    opzioni: {
      A: 'Affronti l\'errore direttamente: lo riconosci, presenti l\'analisi delle cause, proponi correzione e prevenzione. Operativo, senza autoflagellazione visibile.',
      B: 'La vergogna o l\'ansia rendono difficile gestire la situazione con lucidità. Eviti contatti, ripercorri ossessivamente l\'episodio, peggiori la gestione comunicativa.',
      C: 'Riduci al minimo il contatto, rispondi formalmente quando interpellato/a, attraversi le ore senza che il peso dell\'errore atterri completamente.',
      D: 'Riconosci pienamente l\'errore — incluso l\'impatto su altri — e contemporaneamente attivi una correzione che non sia performativa ma sostanziale.',
    },
  },
  {
    id: 5,
    cluster: 'standard',
    titolo: 'Escluso senza spiegazione',
    testo: 'Realizzi che un gruppo significativo per te ha preso una decisione, organizzato qualcosa o costruito un\'iniziativa senza coinvolgerti, e nessuno te lo ha comunicato.\n\nCosa fai nelle 24 ore successive?',
    opzioni: {
      A: 'Acquisisci informazioni in modo ordinato: chi ha deciso cosa, quando, perché. Solo poi decidi se e come reagire.',
      B: 'Confronti qualcuno del gruppo con il tuo malessere prima di aver ricostruito la situazione, esponendoti in un modo che non controlli pienamente.',
      C: 'Non fai nulla. Ti ritiri in silenzio. L\'episodio non viene affrontato né con te stesso/a né con gli altri.',
      D: 'Verifichi i fatti, riconosci a te stesso/a il fastidio, e affronti la cosa solo se vale la pena — calibrando il quanto e il come.',
    },
  },
  {
    id: 6,
    cluster: 'standard',
    titolo: 'Il superiore che ti umilia',
    testo: 'Una figura con potere su di te ti umilia in un contesto pubblico o semi-pubblico. Il comportamento è oggettivamente fuori scala. Reagire ha costi reali; non reagire ha costi diversi.\n\nCome rispondi nel momento?',
    opzioni: {
      A: 'Mantieni la postura, rispondi sul contenuto in modo neutro, registri mentalmente l\'episodio per gestirlo nei canali appropriati. Nessuna reazione emotiva visibile.',
      B: 'La tua reazione tradisce l\'impatto subìto: voce alterata, replica fuori controllo, o blocco visibile. La situazione gestisce te invece del contrario.',
      C: 'Diventi opaco/a. Non rispondi nel merito, non reagisci, non lasci trasparire nulla. Sopprimi l\'episodio in tempo reale come se non stesse accadendo.',
      D: 'Riconosci la situazione per ciò che è, segnali con compostezza che il modo non è accettabile senza scendere allo stesso registro, e prendi nota per il dopo.',
    },
  },
  {
    id: 7,
    cluster: 'standard',
    titolo: 'La fiducia violata da un collega',
    testo: 'Una persona con cui lavori — in cui avevi riposto fiducia — ha agito contro di te in un modo che non ti aspettavi: una manipolazione, un\'informazione tradita, un sabotaggio sottile ma chiaro.\n\nCome gestisci la situazione nei giorni immediatamente successivi?',
    opzioni: {
      A: 'Affronti la situazione con pragmatismo strategico: contieni il danno, valuti chi sa cosa, ricalibri le relazioni sulla base delle informazioni aggiornate.',
      B: 'Confronti la persona con tutto il peso emotivo del tradimento, oppure la tagli fuori completamente senza comunicazione — in entrambi i casi in modo reattivo, non deliberato.',
      C: 'Fai molto poco. Ti ritiri dalla situazione e dalla persona senza affrontarla attivamente.',
      D: 'Affronti il tradimento in modo diretto ma proporzionato: con la persona coinvolta, con chiarezza, senza farne una performance.',
    },
  },
  {
    id: 8,
    cluster: 'crisi',
    titolo: 'La relazione che finisce senza preavviso',
    testo: 'La persona con cui condividevi la tua vita ti comunica che è finita. Non hai avuto modo di prepararti.\n\nNelle prime ore dopo, cosa accade dentro di te?',
    opzioni: {
      A: 'Cerchi di capire cosa è andato storto. Costruisci un modello causale dell\'accaduto, organizzi le informazioni, cerchi la logica di una sequenza che non ti aspettavi.',
      B: 'Senti il dolore in modo diretto e fisico. Il disorientamento è reale. Qualcosa di fondativo si è rotto e il tuo sistema emotivo lo registra con piena intensità.',
      C: 'Una strana anestesia. L\'informazione è arrivata ma non ha attecchito completamente. Funzioni, ma da dietro un vetro.',
      D: 'Senti il dolore per intero — è grave e reale — e allo stesso tempo cominci a orientarti nella nuova realtà senza negare il peso di quello che è appena successo.',
    },
  },
  {
    id: 9,
    cluster: 'crisi',
    titolo: 'Il lavoro che scompare',
    testo: 'Perdi il lavoro in modo improvviso. Non era prevedibile. La sicurezza economica è compromessa nel medio termine; l\'identità professionale che avevi costruito viene azzerata in poche ore.\n\nNelle prime ore, cosa accade dentro di te?',
    opzioni: {
      A: 'Inizi immediatamente a mappare la situazione: liquidità disponibile, network attivabile, opzioni nei prossimi 30/60/90 giorni. L\'ansia si registra ma resta sullo sfondo.',
      B: 'Senti un\'ondata di paura e disorientamento che occupa tutto il sistema. La perdita non è solo economica — è identitaria, e lo senti per intero.',
      C: 'Una piattezza inquietante. La notizia non riesce a generare la reazione che ti aspetteresti. Funzioni, ma c\'è qualcosa che non si è acceso.',
      D: 'Senti il colpo per intero — economico e identitario — e quasi contemporaneamente la mente comincia a costruire mappe operative sul cosa adesso.',
    },
  },
  {
    id: 10,
    cluster: 'crisi',
    titolo: 'La diagnosi che cambia la prospettiva',
    testo: 'Ricevi una diagnosi medica grave o cronica. Non è terminale, ma altera in modo permanente la tua relazione con il tuo corpo, il tuo tempo e la tua mortalità.\n\nNelle prime ore dopo aver ricevuto la diagnosi, cosa accade dentro di te?',
    opzioni: {
      A: 'Inizi a raccogliere informazioni: cosa sappiamo, cosa è il prognosi reale, cosa puoi fare. La componente emotiva resta in sospensione mentre la mente lavora.',
      B: 'Senti la paura in modo viscerale. La mortalità — la tua mortalità — è entrata in stanza in un modo che non era mai stato così concreto. Il sistema emotivo prende lo spazio.',
      C: 'Una distanza strana. Stai ascoltando informazioni su qualcun altro. Funzioni in modo composto ma qualcosa di essenziale non sta atterrando.',
      D: 'Senti la paura piena di quello che hai appena saputo, e contemporaneamente la mente comincia a fare i conti con la nuova realtà — senza minimizzarla né drammatizzarla.',
    },
  },
  {
    id: 11,
    cluster: 'crisi',
    titolo: 'Qualcuno che ami smette di esistere',
    testo: 'Una persona centrale per te muore. È improvviso, o è prevedibile ma comunque devastante quando accade. Il vuoto è immediato e totale.\n\nNelle prime ore, cosa accade dentro di te?',
    opzioni: {
      A: 'La mente prende il comando: cosa va organizzato, chi va contattato, quali sono le procedure. L\'attivazione operativa precede e contiene l\'elaborazione emotiva.',
      B: 'Il dolore è primario, fisico, totale. Il sistema emotivo registra la perdita con la piena intensità che le compete. Funzionare è secondario.',
      C: 'Una strana assenza di reazione. Le informazioni arrivano ma il dolore atteso non si attiva. Operi su un piano apparentemente normale che non corrisponde a quello che sta succedendo.',
      D: 'Senti il dolore per intero, lasci che accada, e contemporaneamente fai quello che va fatto, senza che la funzionalità sia anestesia né che il dolore sia paralisi.',
    },
  },
  {
    id: 12,
    cluster: 'cigno_nero',
    titolo: 'Testimone di un collasso improvviso',
    testo: 'Sei in uno spazio pubblico affollato. La persona davanti a te si accascia in un\'emergenza medica acuta. Le persone intorno sono ferme. Nessuno si muove.\n\nCosa fai nei primi sessanta secondi?',
    opzioni: {
      A: 'Verifichi la sicurezza della scena, valuti la responsività, chiami o dirigi qualcuno a chiamare i soccorsi, inizi le procedure di primo soccorso se le conosci. Sistematico.',
      B: 'Agisci, ma il tuo stato è visibile — la voce trema quando chiedi aiuto, hai un momento di blocco, le azioni non sono completamente coordinate.',
      C: 'Agisci in modo efficiente, senza distress visibile, in una modalità quasi meccanica. Le persone intorno sono sorprese dalla tua calma.',
      D: 'Agisci in modo efficace e resti presente a quello che accade — alla persona a terra e alle persone intorno che potrebbero essere in panico.',
    },
  },
  {
    id: 13,
    cluster: 'cigno_nero',
    titolo: 'La minaccia fisica diretta',
    testo: 'Ti trovi in una situazione che scala verso il pericolo fisico reale. Il pericolo è concreto e immediato. Non c\'è una via di uscita ovvia.\n\nCosa fai nei secondi critici?',
    opzioni: {
      A: 'Agisci sull\'opzione razionalmente più valida disponibile — de-escalation, uscita, protezione, o confronto diretto — in base a quello che la situazione richiede, senza distorsione emotiva.',
      B: 'La tua risposta è guidata più dallo stato emotivo che da una lettura chiara della situazione. Potresti bloccarti, agire impulsivamente, o fare qualcosa che non serve la tua sicurezza.',
      C: 'Il corpo agisce quasi prima che la mente decida. L\'azione è pulita e fredda. Stai operando su qualcosa di vicino all\'automatico.',
      D: 'Scegli la tua azione con una combinazione di velocità e chiarezza. La paura è carburante, non rumore.',
    },
  },
  {
    id: 14,
    cluster: 'cigno_nero',
    titolo: 'La catastrofe che distrugge il contesto fisico',
    testo: 'Un evento improvviso — incendio, crollo, disastro naturale — colpisce il tuo spazio vitale. Hai pochi minuti per agire. Le risorse che davi per scontate non ci sono più.\n\nCosa fai nei primi minuti?',
    opzioni: {
      A: 'Esegui in sequenza: persone prima, documenti essenziali poi, beni recuperabili dopo. La logica della priorità funziona anche in emergenza.',
      B: 'L\'ansia rende disorganizzata la sequenza. Prendi cose insensate, ne dimentichi di essenziali, perdi tempo in scelte che non valgono il rischio.',
      C: 'Una freddezza quasi inquietante. Esegui le azioni necessarie senza che il peso emotivo della perdita atterri in tempo reale.',
      D: 'Agisci in modo ordinato e rapido riconoscendo nello stesso momento l\'impatto di quello che sta succedendo. Senti la perdita e funzioni comunque.',
    },
  },
  {
    id: 15,
    cluster: 'cigno_nero',
    titolo: 'La vita di qualcuno dipende da te adesso',
    testo: 'Sei l\'unica persona disponibile che può intervenire per evitare un esito potenzialmente fatale per qualcun altro. Hai informazioni imperfette e pressione temporale reale.\n\nCosa fai con informazioni imperfette e pressione temporale reale?',
    opzioni: {
      A: 'Prendi la migliore decisione disponibile con le informazioni che hai, la esegui, e rimani adattabile se la situazione evolve. Non aspetti la certezza.',
      B: 'La pressione di agire senza sufficiente certezza ti blocca per un momento, o ti spinge verso una decisione subottimale guidata dall\'urgenza di fare qualcosa piuttosto che di fare la cosa giusta.',
      C: 'Agisci con una freddezza che dopo ti sorprende. Nel momento, esiste solo il problema e l\'azione. Nient\'altro entra nel campo.',
      D: 'Agisci con decisione usando quello che hai, resti presente all\'evolversi della situazione, e aggiusti. Sei veloce senza essere impulsivo/a.',
    },
  },
]

export const ITEM_LIKERT = [
  { id: 16, dimensione: 'NFC', testo: 'Quando analizzo un problema, la soddisfazione vera arriva solo dopo aver identificato il meccanismo causale, non quando ho trovato una soluzione che funziona.' },
  { id: 17, dimensione: 'NFC', testo: 'Mi capita regolarmente di continuare a ragionare su un problema anche dopo aver trovato una risposta soddisfacente, perché sospetto che ci sia qualcosa che non torna.' },
  { id: 18, dimensione: 'NFC', reverse: true, testo: 'Quando qualcuno mi presenta un\'analisi complessa, la mia tendenza è semplificarla il prima possibile per renderla gestibile.' },
  { id: 19, dimensione: 'NFC', reverse: true, testo: 'Preferisco una risposta rapida e approssimativa a una risposta lenta e precisa: il tempo ha un costo che l\'analisi raramente ripaga.' },
  { id: 20, dimensione: 'NFC', testo: 'Capire perché qualcosa funziona mi interessa quanto, se non più, del fatto che funzioni.' },
  { id: 21, dimensione: 'NFC', testo: 'Quando mi trovo di fronte a due teorie ugualmente plausibili, l\'incertezza tra di esse non mi genera ansia: la mantengo attiva finché non ho dati sufficienti per scioglierla.' },
  { id: 22, dimensione: 'FI', testo: 'Quando il mio istinto e l\'analisi sistematica divergono, la mia prima reazione è dubitare dell\'analisi, non dell\'istinto.' },
  { id: 23, dimensione: 'FI', testo: 'Riesco a percepire quando una situazione o una persona "non torna" molto prima di riuscire a spiegare razionalmente perché.' },
  { id: 24, dimensione: 'FI', testo: 'Le sensazioni corporee che provo di fronte a una scelta difficile — tensione, accelerazione, malessere diffuso — sono informazioni affidabili che prendo sul serio.' },
  { id: 25, dimensione: 'FI', reverse: true, testo: 'Non mi fido di una decisione se non riesco a giustificarla con criteri espliciti e verificabili da chiunque.' },
  { id: 26, dimensione: 'FI', reverse: true, testo: 'Le mie intuizioni sulle persone si rivelano sbagliate con una frequenza che mi impedisce di considerarle affidabili.' },
  { id: 27, dimensione: 'FI', testo: 'Quando ho una sensazione forte e persistente su qualcosa, quella sensazione rimane anche dopo che l\'analisi razionale la smentisce — e non sempre è la sensazione ad avere torto.' },
  { id: 28, dimensione: 'CS', testo: 'Quando sono sotto pressione intensa, provo emozioni forti, ma scelgo in modo deliberato di non lasciarle guidare le mie azioni in quel momento.' },
  { id: 29, dimensione: 'CS', testo: 'La mia capacità di restare funzionale in situazioni di crisi non dipende dal non sentire nulla: dipende dal decidere io quando e quanto spazio dare a ciò che sento.' },
  { id: 30, dimensione: 'CS', flag: 'anestesia', testo: 'Di fronte al dolore o alla sofferenza degli altri, faccio fatica a identificare qualcosa che potrei definire empatia genuina: registro l\'informazione, ma non mi tocca visceralmente.' },
  { id: 31, dimensione: 'CS', testo: 'Il distacco che mostro in certi contesti è una scelta tattica consapevole, non il mio stato emotivo di default.' },
  { id: 32, dimensione: 'CS', reverse: true, testo: 'In situazioni di forte tensione emotiva, le mie emozioni mi travolgono in misura tale da compromettere la mia capacità di giudizio.' },
  { id: 33, dimensione: 'CS', flag: 'anestesia', testo: 'Non ho mai capito perché le persone vengano sopraffatte emotivamente da eventi che, analizzati a mente fredda, risultano gestibili: la risposta emotiva intensa mi sembra quasi sempre sproporzionata.' },
  { id: 34, dimensione: 'CS', testo: 'Mostrare vulnerabilità emotiva in contesti professionali non mi sembra né utile né pertinente, non perché provi vergogna, ma perché valuto che non apporti alcun valore funzionale alla situazione.' },
  { id: 35, dimensione: 'PR', testo: 'Se domani accadesse un evento catastrofico e del tutto imprevedibile, sono genuinamente convinto che la mia capacità di adattamento sarebbe superiore alla media delle persone che conosco.' },
  { id: 36, dimensione: 'PR', testo: 'Ho già elaborato mentalmente scenari estremi con sufficiente dettaglio da sapere come reagirei: non mi coglierebbe del tutto impreparato.' },
  { id: 37, dimensione: 'PR', reverse: true, testo: 'Riconosco onestamente che, di fronte a un vero Cigno Nero, la mia risposta sarebbe probabilmente disorganizzata quanto quella di chiunque altro.' },
  { id: 38, dimensione: 'PR', testo: 'La mia resilienza non si fonda sull\'assenza di paura: si fonda su principi operativi e strutture cognitive che rimangono funzionali anche quando la paura è presente.' },
  { id: 39, dimensione: 'PR', reverse: true, testo: 'La convinzione di essere resiliente è, almeno in parte, una narrazione che mi racconto per sentirmi al sicuro: non so davvero come reagirei a qualcosa di veramente catastrofico.' },
  { id: 40, dimensione: 'PR', reverse: true, testo: 'La mia capacità di gestire eventi estremi non è mai stata testata davvero: non ho basi concrete per affermare con certezza cosa farei.' },
]
